const Actions = {
  SET_EMAIL: 'SET_EMAIL',
  SET_LOGIN_COOKIE: 'SET_LOGIN_COOKIE',
  SET_PREVIOUS_PATH: 'SET_PREVIOUS_PATH',
  SET_USER_ID: 'SET_USER_ID',
  SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
  SET_BUSINESS_BY_ID: 'SET_BUSINESS_BY_ID',
  SET_USER: 'SET_USER',
  SET_BUSINESS_ID: 'SET_BUSINESS_ID',
  SET_TUTORIAL_ID: 'SET_TUTORIAL_ID'
}

export default Actions
